/*

Simple rock, paper, scissors game

*/

#include <iostream>
#include <cstdlib>
#include <ctime>
#include <cctype>
using namespace std;

const int ROCK = 1, PAPER = 2, SCISSORS = 3;

/*
A random number in the range of 1 - 3 is generated by the computer.
This will be the computer's choice
*/
int computerChoice(int cChoice) {
    unsigned seed = time(0);
    srand(seed);

    return (rand() % (SCISSORS - ROCK + 1)) + ROCK;
}


/*
Ask the user to make a choice.
*/
int userChoice() {
    int uChoice;
    int isValid = false;
    
    while(!isValid) {
        cout << "Enter 1 for Rock, 2 for Paper, or 3 for Scissors: ";
        cin >> uChoice;

        if(cin.fail() || uChoice < ROCK || uChoice > SCISSORS) {
            cin.clear();
            cin.ignore(numeric_limits<streamsize>::max(), '\n');
            cout << "Invalid Input! ";
        }
        else isValid = true;
    }

    return uChoice;
}


/*
Computer's choice is shown
*/
void showComputerChoice(int cChoice) {
    cout << "\nThe Computer Chose: ";

    if(cChoice == ROCK) cout << "Rock" << endl;
    else if(cChoice == PAPER) cout << "Paper" << endl;
    else cout << "Scissors" << endl;
}

/*
User's choice is shown
*/
void showUserChoice(int uChoice) {
    cout << "\nYou Chose: ";

    if(uChoice == ROCK) cout << "Rock" << endl;
    else if(uChoice == PAPER) cout << "Paper" << endl;
    else cout << "Scissors" << endl;
}


/*
Winner is decided
*/
void findWinner(int cChoice, int uChoice, bool& play) {
    //computer chose rock
    if(cChoice == ROCK) {
        if(uChoice == ROCK) { //tie
            cout << "\nIt's a tie! You both picked rock. Try again." << endl;
            play = true;
            return;
        }
        else if(uChoice == PAPER) { //user won
            cout << "\nPaper beats rock! Congradualtions, you won!" << endl;
            play = false;
            return;
        }
        else if(uChoice == SCISSORS) { //computer won
            cout << "\nRock beats scissors. The computer won. You lost." << endl;
            play = false;
            return;
        }
    }
    //computer chose paper
    else if(cChoice == PAPER) {
        if(uChoice == ROCK) { //computer won
            cout << "\nPaper beats rock. The computer won. You lost." << endl;
            play = false;
            return;
        }
        else if(uChoice == PAPER) { //tie
            cout << "\nIt's a tie! You both picked paper. Try again." << endl;
            play = true;
            return;
        }
        else if(uChoice == SCISSORS) { //user won
            cout << "\nScissors beat paper! Congradualtions, you won!" << endl; 
            play = false;
            return;
        }
    }
    //computer chose scissors
    else if(cChoice == SCISSORS) {
        if(uChoice == ROCK) { //user won
            cout << "\nRock beats scissors! Congradualtions, you won!" << endl;
            play = false;
            return;
        }
        else if(uChoice == PAPER) { //computer won
            cout << "\nScissors beats paper. The computer won. You lost." << endl;
            play = false;
            return;
        }
        else if(uChoice == SCISSORS) { //tie
            cout << "\nIt's a tie! You both picked scissors. Try again." << endl;
            play = true;
            return;
        }
    }
}


int main() {
    int cChoice;
    int uChoice;

    cout << "Hello! Let's play a game of rock, paper, scissors!" << endl;

    bool playing = true;
    while(playing) {
        cChoice = computerChoice(cChoice);
        uChoice = userChoice();

        showComputerChoice(cChoice);
        showUserChoice(uChoice);

        findWinner(cChoice, uChoice, playing);
    }
}
